package main

import (
	"fmt"
)

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
 */

func fibonacci() func(int) int {
	prev := 1
	return func(x int) int {
		sum := x + prev
		prev = x
		return sum
	}
}
func main() {
	s := fibonacci()
	val := 2
	sum := 0
	for ; val < 4000000; {
		if val % 2 == 0 {
			sum += val
		}
		val = s(val)
	}
	fmt.Printf("%d\n", sum)

}
